FROM python:3.11-slim-bullseye

WORKDIR /usr/src/app

RUN apt-get update \
    && apt-get install -y curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH="${PYTHONPATH}:/usr/src/app"

EXPOSE 8000

CMD [ "python", "./main.py" ]

